#!/usr/bin/env bash

# command taken from https://github.com/JLLeitschuh/ktlint-gradle  task addKtlintFormatGitPreCommitHook
filesToFormat="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.java|\.kt/ { print $NF}')"

if [ -z "$filesToFormat" ]; then
   echo "Skipping spotless"
else
	echo "Running mvn spotless:apply"
	echo "Files to format"
	for sourceFilePath in $filesToFormat
	do
	  echo "$sourceFilePath"
	done

	mvn spotless:apply
	git add .
fi

